version: 2
jobs:
  test:
    working_directory: ~/gathee
    docker:
      - image: circleci/python:3.7-browsers-legacy
      - image: circleci/postgres:9.6.9-alpine
    steps:
      - checkout
      - run:
          name: Set up environment
          command: |
            sudo pip install pipenv==2018.11.26
            pipenv install
      - run:
          name: Run Tests
          command: |
            cd src/core
            pipenv run python manage.py test
workflows:
  version: 2
  test-application:
    jobs:
      - test
