# Generated by Django 2.2.7 on 2019-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'The username address you entered has already been registered.'}, max_length=40, unique=True, verbose_name='username'),
        ),
    ]
