# Generated by Django 2.2.7 on 2019-11-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demovideo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
