# Generated by Django 2.2.7 on 2019-11-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_demovideo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demovideo',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/demo', verbose_name='Select Video:'),
        ),
        migrations.AlterField(
            model_name='premiumvideo',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/premium', verbose_name='Select Video:'),
        ),
    ]
