# Generated by Django 2.2.7 on 2019-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20191126_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demovideo',
            name='description',
        ),
        migrations.AddField(
            model_name='premiumvideo',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
