# Generated by Django 2.2.7 on 2019-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
                ('video_file', models.FileField(null=True, upload_to='videos', verbose_name='Select Video:')),
            ],
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='PremiumVideo',
        ),
    ]
