# Generated by Django 2.2.7 on 2019-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20191121_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='change_email_tracker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=67),
            preserve_default=False,
        ),
    ]
