# Generated by Django 2.2.7 on 2019-11-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20191126_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demovideo',
            options={'verbose_name_plural': 'Demo Videos'},
        ),
        migrations.AlterModelOptions(
            name='premiumvideo',
            options={'verbose_name_plural': 'Premium Videos Tutorials'},
        ),
        migrations.AlterModelOptions(
            name='premiumvideodemo',
            options={'verbose_name_plural': 'Associate A video demo with its Tutorial'},
        ),
    ]
