# Generated by Django 2.2.7 on 2019-11-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20191126_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumvideo',
            options={'verbose_name_plural': 'Premium Video Tutorials'},
        ),
    ]
