# Generated by Django 2.2.7 on 2019-11-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20191126_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demovideo',
            name='course',
        ),
        migrations.CreateModel(
            name='PremiumVideoDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.DemoVideo')),
                ('premium_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.PremiumVideo')),
            ],
            options={
                'verbose_name_plural': 'Premium Videos Demos',
            },
        ),
    ]
