# Generated by Django 2.2.7 on 2019-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20191126_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(null=True, upload_to='images/courses/'),
        ),
    ]
