# Generated by Django 2.2.7 on 2019-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('about_totor', models.CharField(max_length=600)),
                ('tutor_image', models.ImageField(null=True, upload_to='images/courses/')),
            ],
        ),
    ]
