# Generated by Django 2.2.7 on 2019-12-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Register Users for a Course'},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student', 'course')},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=40, unique=True)),
                ('timeslot_duration', models.DurationField(default='00:00:00', help_text='[DD (days)] [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subscriptions.Course')),
            ],
        ),
    ]
