# Generated by Django 2.2.7 on 2019-12-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_auto_20191213_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='timeslot_duration',
            new_name='duration',
        ),
    ]
