# Generated by Django 2.2.7 on 2019-12-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20191213_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default='00:00:00:00', help_text='[DD (days)] [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration'),
        ),
    ]
