# Generated by Django 2.2.7 on 2019-12-16 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_auto_20191213_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Add lessons for courses'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default='00:00:00', help_text='[DD (days)] (leave a space between day             and hour min sec) [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration'),
        ),
        migrations.CreateModel(
            name='PendingCourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'View users who have sent request to join courses',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
