# Generated by Django 2.2.7 on 2019-12-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20191216_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingcourserequest',
            unique_together=set(),
        ),
    ]
