# Generated by Django 2.2.7 on 2019-12-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20191216_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingcourserequest',
            unique_together={('student', 'course')},
        ),
    ]
