# Generated by Django 2.2.7 on 2019-12-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20191216_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('video_file', models.FileField(null=True, upload_to='lessons', verbose_name='Select Video:')),
                ('description', models.CharField(max_length=500, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_videos', to='subscriptions.Lesson')),
            ],
            options={
                'verbose_name_plural': 'Lesson Video Tutorials',
                'unique_together': {('video_file', 'lesson')},
            },
        ),
    ]
