# Generated by Django 2.2.7 on 2019-12-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_lessonvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(null=True, upload_to='images/lessons/'),
        ),
        migrations.CreateModel(
            name='LessonVideoDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.DemoVideo')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Lesson')),
            ],
            options={
                'verbose_name_plural': 'Associate A video demo with its Lesson',
                'unique_together': {('demo_video', 'lesson')},
            },
        ),
    ]
