# Generated by Django 2.2.7 on 2019-12-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_auto_20191218_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_number',
            new_name='lesson_position',
        ),
    ]
