# Generated by Django 2.2.7 on 2019-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_auto_20191219_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Designates whether the lesson is currently being viewed.', verbose_name='viewing status'),
        ),
    ]
