# Generated by Django 2.2.7 on 2019-12-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_lesson_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='is_current',
            new_name='is_viewed',
        ),
    ]
