# Generated by Django 2.2.7 on 2019-12-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_lesson_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
    ]
