# Generated by Django 2.2.7 on 2019-12-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_remove_lesson_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
