# Generated by Django 2.2.7 on 2019-12-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_lesson_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
        migrations.AddField(
            model_name='student',
            name='is_allowed',
            field=models.BooleanField(default=False, help_text='Check to ascertain user can view this course.', verbose_name='viewing status'),
        ),
    ]
