# Generated by Django 2.2.7 on 2019-12-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_auto_20191220_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_position',
            field=models.IntegerField(help_text='The position of the lesson in the course'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('lesson_position', 'course')},
        ),
    ]
