# Generated by Django 2.2.7 on 2019-12-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_auto_20191220_0202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('lesson_position', 'course', 'title')},
        ),
    ]
