# Generated by Django 2.2.7 on 2019-12-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_auto_20191220_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'title', 'lesson_position')},
        ),
    ]
