# Generated by Django 2.2.8 on 2019-12-20 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_auto_20191220_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_viewed',
        ),
        migrations.CreateModel(
            name='ViewedLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False, help_text='Designates whether the lesson is currently being viewed.', verbose_name='viewing status')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
