# Generated by Django 2.2.8 on 2019-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_auto_20191220_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='role',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
