# Generated by Django 2.2.8 on 2019-12-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0033_tutor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='contact',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
