# Generated by Django 2.2.8 on 2019-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0034_tutor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=255)),
                ('address_line_two', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
