# Generated by Django 2.2.8 on 2019-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0035_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
